name: flutter_checker
description: A sample command-line application align the system Flutter installation with the current project defined version
version: 0.0.2
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.3

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  yaml: ^3.1.2

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
